{
 "title": "Default",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kubernetes CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "kubernetes_pod_cpu" }
   ]
  },
  {
   "title": "Kubernetes memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "kubernetes_pod_memory" }
   ]
  },
  {
   "title": "Active players",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_players" }
   ]
  },
  {
   "title": "Startup delay",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "playback_startup_delay" }
   ]
  },
  {
   "title": "Stalls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_stalls" }
   ]
  },
  {
   "title": "Dropped frames",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_dropped_frames" }
   ]
  },
  {
   "title": "Total dropped frames",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(playback_dropped_frames[1h])"
    }
   ]
  }
 ]
}