{
 "title": "Media servers",
 "time": { "from": "2019-12-29T12:26:54.452Z", "to": "2019-12-29T12:37:52.034Z" },
 "panels": [
  {
   "title": "Kubernetes pod CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "kubernetes_pod_cpu", "legendFormat": "{{container}}" }
   ]
  },
  {
   "title": "Kubernetes pod memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "kubernetes_pod_memory", "legendFormat": "{{container}}" }
   ]
  },
  {
   "title": "Active players",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_players", "legendFormat": " " }
   ]
  },
  {
   "title": "Startup delay",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "playback_startup_delay", "legendFormat": "id-{{playerId}}" }
   ]
  },
  {
   "title": "Average startup delay",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "avg(playback_startup_delay)", "legendFormat": " " }
   ]
  },
  {
   "title": "Received frames",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_received_frames", "legendFormat": "id-{{playerId}}" }
   ]
  },
  {
   "title": "Total received frames",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(playback_received_frames[10m])",
     "legendFormat": "id-{{playerId}}"
    }
   ]
  },
  {
   "title": "Average received frames",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(playback_received_frames)", "legendFormat": " " }
   ]
  },
  {
   "title": "Lost frames",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_lost_frames", "legendFormat": "id-{{playerId}}" }
   ]
  },
  {
   "title": "Total lost frames",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(playback_lost_frames[10m])",
     "legendFormat": "id-{{playerId}}"
    }
   ]
  },
  {
   "title": "Average lost frames",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(playback_lost_frames)", "legendFormat": " " }
   ]
  },
  {
   "title": "Lost samples",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_lost_samples", "legendFormat": "id-{{playerId}}" }
   ]
  },
  {
   "title": "Total lost samples",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(playback_lost_samples[10m])",
     "legendFormat": "id-{{playerId}}"
    }
   ]
  },
  {
   "title": "Received samples",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_received_samples", "legendFormat": "id-{{playerId}}" }
   ]
  },
  {
   "title": "Total received samples",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(playback_received_samples[10m])",
     "legendFormat": "id-{{playerId}}"
    }
   ]
  }
 ]
}