apiVersion: v1
kind: Service
metadata:
  name: icecast-cloud-launcher
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: icecast