apiVersion: v1
kind: Service
metadata:
  name: icecast-cloud-stream
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    app: icecast