{
 "title": "Default",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Kubernetes CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "kubernetes_pod_cpu" }
   ]
  },
  {
   "title": "Active players",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_players" }
   ]
  },
  {
   "title": "Startup delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "playback_startup_delay" }
   ]
  },
  {
   "title": "Kubernetes memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "kubernetes_pod_memory" }
   ]
  },
  {
   "title": "Dropped frames",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_dropped_frames" }
   ]
  },
  {
   "title": "Stalls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "playback_stalls" }
   ]
  }
 ]
}