apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-47
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30047
      targetPort: 30047
      nodePort: 30047
  selector:
    app: kms
