apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-35
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30035
      targetPort: 30035
      nodePort: 30035
  selector:
    app: kms
