apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-19
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30019
      targetPort: 30019
      nodePort: 30019
  selector:
    app: kms
