apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-14
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30014
      targetPort: 30014
      nodePort: 30014
  selector:
    app: kms
