apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-65
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30065
      targetPort: 30065
      nodePort: 30065
  selector:
    app: kms
