apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-15
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30015
      targetPort: 30015
      nodePort: 30015
  selector:
    app: kms
