apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-89
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30089
      targetPort: 30089
      nodePort: 30089
  selector:
    app: kms
