apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-64
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30064
      targetPort: 30064
      nodePort: 30064
  selector:
    app: kms
