apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-97
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30097
      targetPort: 30097
      nodePort: 30097
  selector:
    app: kms
