apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-90
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30090
      targetPort: 30090
      nodePort: 30090
  selector:
    app: kms
