apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-54
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30054
      targetPort: 30054
      nodePort: 30054
  selector:
    app: kms
