apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-7
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30007
      targetPort: 30007
      nodePort: 30007
  selector:
    app: kms
