apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-72
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30072
      targetPort: 30072
      nodePort: 30072
  selector:
    app: kms
