apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-39
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30039
      targetPort: 30039
      nodePort: 30039
  selector:
    app: kms
