apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-16
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30016
      targetPort: 30016
      nodePort: 30016
  selector:
    app: kms
