apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-83
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30083
      targetPort: 30083
      nodePort: 30083
  selector:
    app: kms
