apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-80
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30080
      targetPort: 30080
      nodePort: 30080
  selector:
    app: kms
