apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-20
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30020
      targetPort: 30020
      nodePort: 30020
  selector:
    app: kms
