apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-61
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30061
      targetPort: 30061
      nodePort: 30061
  selector:
    app: kms
