apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-22
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30022
      targetPort: 30022
      nodePort: 30022
  selector:
    app: kms
