apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-56
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30056
      targetPort: 30056
      nodePort: 30056
  selector:
    app: kms
