apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-84
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30084
      targetPort: 30084
      nodePort: 30084
  selector:
    app: kms
