apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-70
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30070
      targetPort: 30070
      nodePort: 30070
  selector:
    app: kms
