apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-62
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30062
      targetPort: 30062
      nodePort: 30062
  selector:
    app: kms
