apiVersion: v1
kind: Service
metadata:
  name: red5-cloud-launcher
spec:
  type: NodePort
  ports:
    - name: launcher-http
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: red5