apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-63
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30063
      targetPort: 30063
      nodePort: 30063
  selector:
    app: kms
