apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-33
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30033
      targetPort: 30033
      nodePort: 30033
  selector:
    app: kms
