apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-51
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30051
      targetPort: 30051
      nodePort: 30051
  selector:
    app: kms
