apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-86
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30086
      targetPort: 30086
      nodePort: 30086
  selector:
    app: kms
