apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-59
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30059
      targetPort: 30059
      nodePort: 30059
  selector:
    app: kms
