apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-24
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30024
      targetPort: 30024
      nodePort: 30024
  selector:
    app: kms
