apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-82
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30082
      targetPort: 30082
      nodePort: 30082
  selector:
    app: kms
