apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-9
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30009
      targetPort: 30009
      nodePort: 30009
  selector:
    app: kms
