apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-17
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30017
      targetPort: 30017
      nodePort: 30017
  selector:
    app: kms
