apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-69
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30069
      targetPort: 30069
      nodePort: 30069
  selector:
    app: kms
