apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-37
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30037
      targetPort: 30037
      nodePort: 30037
  selector:
    app: kms
