apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-29
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30029
      targetPort: 30029
      nodePort: 30029
  selector:
    app: kms
