apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-93
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30093
      targetPort: 30093
      nodePort: 30093
  selector:
    app: kms
