apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-44
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30044
      targetPort: 30044
      nodePort: 30044
  selector:
    app: kms
