apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-45
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30045
      targetPort: 30045
      nodePort: 30045
  selector:
    app: kms
