apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-46
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30046
      targetPort: 30046
      nodePort: 30046
  selector:
    app: kms
