apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-36
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30036
      targetPort: 30036
      nodePort: 30036
  selector:
    app: kms
