apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-5
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30005
      targetPort: 30005
      nodePort: 30005
  selector:
    app: kms
