apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-87
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30087
      targetPort: 30087
      nodePort: 30087
  selector:
    app: kms
