apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-30
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30030
      targetPort: 30030
      nodePort: 30030
  selector:
    app: kms
