apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-23
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30023
      targetPort: 30023
      nodePort: 30023
  selector:
    app: kms
