apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-6
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30006
      targetPort: 30006
      nodePort: 30006
  selector:
    app: kms
