apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-100
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30100
      targetPort: 30100
      nodePort: 30100
  selector:
    app: kms
