apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-81
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30081
      targetPort: 30081
      nodePort: 30081
  selector:
    app: kms
