apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-60
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30060
      targetPort: 30060
      nodePort: 30060
  selector:
    app: kms
