apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-57
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30057
      targetPort: 30057
      nodePort: 30057
  selector:
    app: kms
