apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-27
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30027
      targetPort: 30027
      nodePort: 30027
  selector:
    app: kms
