apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-91
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30091
      targetPort: 30091
      nodePort: 30091
  selector:
    app: kms
