apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-31
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30031
      targetPort: 30031
      nodePort: 30031
  selector:
    app: kms
