apiVersion: v1
kind: Service
metadata:
  name: kms-cloud-webrtc-41
  labels:
    nodePort: webrtc
spec:
  type: NodePort
  ports:
    - name: webrtc
      port: 30041
      targetPort: 30041
      nodePort: 30041
  selector:
    app: kms
