apiVersion: v1
kind: Service
metadata:
  name: vlc-cloud-stream
spec:
  type: NodePort
  ports:
    - name: stream
      port: 8081
      targetPort: 8081
      nodePort: 30001
  selector:
    app: vlc